New STEVX2 Request
icl-utk-edu/plasma pull request #14
Opened 2022-03-03 21:53 UTC by Tony-ICL

This pull requests adds five new files. 1) laneg2 is most similar
to LAPACK laneg, but uses Zhang's scaled Sturm sequence which we
found empirically superior on troublesome matrices. It does a
single bisection.  2) laebz2 uses laneg2 to perform the parallel
work of finding eigenvalues (and optionally eigenvectors) in a
range, of either values or indexes.  Unlike LAPACK laebz, we
handle multiplicity; theoretically this is not necessary on ST
matrices, but on large matrices eigenvalue density can produce
multiple eigenvalues within machine precision of each other, and
the result is multiplicity. laebz2 uses an array of structures
defined in 3) include/plasma_zlaebz2_work. 4) stevx2 is the
show-runner, unlike LAPACK stevx, this includes swapping pairs of
eigenvectors if they perform better, and uses plasma_geqrf to
orthogonalize eigenvectors.  This is a necessary step because
inverse iteration does not guarantee orthogonality, especially
when eigenvalues are close, either absolutely (their difference
is tiny) or relatively (their ratio is very close to 1). 5)
test/test_zstevx2.c is the tester for this code; it uses a Kahan
matrix of size "M" that has directly computable eigenvalues we
can use to verify that we are finding the correct eigenvalues,
and we test the eigenvectors by testing them (without using any
additional memory allocations).  Note that the 'z' precision
files are only a code template, the only code generated is for
single and double precision real (sstevx2, dstevx2). Other files
are changed to incorporate these files into the build system.

2022-03-04 02:19 UTC, luszczek requested changes
There are still many issues like non-conformant code to meet PLASMA coding guidelines. And lots of debugging code leftover. Might need a few more iterations.

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    {
No need for braces for a single call

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    if (0) start_orth = omp_get_wtime();
Ooops. No need for timing. PLASMA has builtin tracing

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    if (ret != 0) {
`plasma_error()` is for reporting errors

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +        exit(-1);
PLASMA never calls `exit()` that's left for the user

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +        exit(-1);
PLASMA never calls `exit()` that's left for the user

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    {free(pQ); pQ = NULL;}
No multiple statements on a single line.

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    if (0) {
No debugging `if(0)`

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +                if(0) fprintf(stderr, "%s:%i Swapping vectors for %d and %d; eigenvalue diff=%.16e.\n", __func__, __LINE__, i, i+1, pVal[i+1]-pVal[i] );
No debugging `if(0)`

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    if (0) fprintf(stderr, "%s:%i globMinEval=%.15f, globMaxEval=%.15f, vl=%.15f vu=%.15f\n",
No debugging `if(0)`

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    for (i=0; i<max_threads; i++) {
There should be line call to `calloc()`. In fact, it should be `malloc()`. The threads just add an offset based on `omp_get_thread_num()`

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    for (i=0; i<max_threads; i++) {
Single `_alloc()` and single `free()`

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +    if(0) fprintf(stderr, "plasma_stevx2 exit with return=%d.\n", sequence.status);
No debugging statements in PLASMA

2022-03-04 02:19 UTC, luszczek commented on compute/zstevx2.c
> +} /* END plasma_zstevx2 */
No function names after closing brace

2022-03-04 02:19 UTC, luszczek commented on include/plasma_types.h
> +    PlasmaStageInit,
`Stage` of what? Reduction to tridiagonal also has stages.

2022-03-04 02:19 UTC, luszczek commented on include/plasma_z.h
> +int plasma_zstevx2(
One so many lines? More than one arg would fit per line

2022-03-04 02:19 UTC, luszczek commented on test/test_zstevx2.c
> +#include <float.h>
Not a standard C header file.

2022-03-04 02:19 UTC, luszczek commented on test/test_zstevx2.c
> +} /* end test_zstevx2 */
No function names after braces

2022-03-04 02:19 UTC, luszczek commented on compute/zlaebz2.c
> +                while (1) {
Looks like a regular `for (;;)`

2022-03-04 02:19 UTC, luszczek commented on compute/zlaebz2.c
> +                if(0) fprintf(stderr, "%2i:%s:%i Exit while(true), found eigenvalue %.16e nLT_low=%d idx=%d numEV=%i.\n", omp_get_thread_num(), __func__, __LINE__, myB->lowerBound, myB->nLT_low, myB-
No debugging in PLASMA code

2022-03-04 02:19 UTC, luszczek commented on compute/zlaebz2.c
> +                if(0) fprintf(stderr, "%2i:%s:%i Getvector ev=%.16e idx=%d\n", omp_get_thread_num(), __func__, __LINE__, myB->lowerBound, myB->nLT_low-Stack->baseIdx);
No debugging in PLASMA code

2022-03-09 17:59 UTC, closed without merging

2022-03-09 18:00 UTC, Tony-ICL commented
Rewrote for style, and to make this an OMP TASK based operation.